# Chapeter 4: array Selection

In [1]:
import numpy as np

In [13]:
x = np.arange(1,11)

In [14]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
x > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
mask = x > 5

In [18]:
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
x[mask]

array([ 6,  7,  8,  9, 10])

In [21]:
4 not in x

False

In [22]:
m = 4 not in x

In [25]:
x[m]

array([], shape=(0, 10), dtype=int64)

In [26]:
print(x[m])

[]

In [41]:
# Create a array that return the value in even numbers
e = np.arange(2, 11, 2)
print(e)

[ 2  4  6  8 10]

In [43]:
# Create array that shart with 1 and end with 101 with two step
x = np.arange(1, 102,2)
print(x)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101]

In [48]:
p = np.array(['raj','roy','ram','raj'])

In [49]:
p!= 'raj'

array([False,  True,  True, False])

In [52]:
q = p != 'raj'

In [54]:
print(p[q])

['roy' 'ram']

In [56]:
p[q] = 'meet'

In [57]:
print(p[q])

['mee' 'mee']

# Pandas
## allwase import pandas and numpy togater

# Chapter 1

In [60]:
import pandas as pd
import numpy as np

import warnings
warnings. filterwarnings("ignore")

# 1. Series
## How to call Series

In [61]:
x = pd.Series()

In [66]:
x

Series([], dtype: object)

In [67]:
print(x)

Series([], dtype: object)

In [69]:
a = pd.Series(data=[1,2,3],index=["a","b","c"])

In [70]:
a

a    1
b    2
c    3
dtype: int64

In [71]:
d = {'a':1,'b':2,'c':3}

In [72]:
a = pd.Series(data = d)

In [73]:
a

a    1
b    2
c    3
dtype: int64

In [74]:
a = pd.Series(data = d , index= ["a","b","c","d"])

In [75]:
a

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [79]:
d = np.array([1,2,3])
i = np.array(["a","b","c"])

In [80]:
b = pd.Series(data = d , index = i)

In [82]:
b

a    1
b    2
c    3
dtype: int64

# 2. DataFrame
## Defination

In [81]:
data = [1,2,3,4,5]
z = pd.DataFrame(data)
z

   0
0  1
1  2
2  3
3  4
4  5

In [83]:
data = [['i','ii','iii'],['alpha','beata','gamma'],['a','c','d']]
z = pd.DataFrame(data,columns=["c1","c2","c3"])
z

      c1     c2     c3
0      i     ii    iii
1  alpha  beata  gamma
2      a      c      d

In [98]:
name = ['Pratik','Purvesh','Faizan','Sandesh','Madhu','Vinayak']
py = [89,78,75,64,45,25]
ml = [89,57,65,78,25,35]
dic ={"Name":name,"Python":py,"ML":ml}

In [115]:
l = pd.DataFrame(dic)
l

      Name  Python  ML
0   Pratik      89  89
1  Purvesh      78  57
2   Faizan      75  65
3  Sandesh      64  78
4    Madhu      45  25
5  Vinayak      25  35

In [106]:
l[l.Name=="Pratik"]

     Name  Python  ML
0  Pratik      89  89

In [114]:
l[l.Python >= 60]

      Name  Python  ML
0   Pratik      89  89
1  Purvesh      78  57
2   Faizan      75  65
3  Sandesh      64  78

In [127]:
# Write a program to create two dimention array in a dataframe and gives colum name and indexing name
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [128]:
z = pd.DataFrame(a,columns=["c1","c2"],index=["r1","r2"])

In [129]:
z

    c1  c2
r1   1   2
r2   3   4

In [130]:
# Create a datafram using any array creation rutin and create a table 10*4 and gives a colom name
b = np.arange(1,41).reshape(10,4)

In [131]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [139]:
u = pd.DataFrame(b,columns=["c1","c2","c3","c4"],index=["r1","r2","r3","r4","r5","r6","r7","r8","r9","r10"])

In [140]:
u

     c1  c2  c3  c4
r1    1   2   3   4
r2    5   6   7   8
r3    9  10  11  12
r4   13  14  15  16
r5   17  18  19  20
r6   21  22  23  24
r7   25  26  27  28
r8   29  30  31  32
r9   33  34  35  36
r10  37  38  39  40