#  Topic 2 DataFrame

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## read_table

In [ ]:
excel_df = pd.read_excel('your_excel_file.xlsx')
excel_df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.tail(5)

    Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
995  Middle East and North Africa,Azerbaijan,Snacks...
996  Europe,Georgia,Baby Food,Offline,H,08-01-2011,...
997  Middle East and North Africa,United Arab Emira...
998  Europe,Finland,Household,Offline,L,1/25/2016,2...
999  Europe,Portugal,Cereal,Offline,C,04-10-2014,81...

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
pf = pd.read_table("sales.csv")

In [ ]:
pf.head(10)

  Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0  Middle East and North Africa,Libya,Cosmetics,O...
1  North America,Canada,Vegetables,Online,M,11-07...
2  Middle East and North Africa,Libya,Baby Food,O...
3  Asia,Japan,Cereal,Offline,C,04-10-2010,1614426...
4  Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/...
5  Europe,Armenia,Cereal,Online,H,11/24/2014,6834...
6  Sub-Saharan Africa,Eritrea,Cereal,Online,H,03-...
7  Europe,Montenegro,Clothes,Offline,M,5/17/2012,...
8  Central America and the Caribbean,Jamaica,Vege...
9  Australia and Oceania,Fiji,Vegetables,Offline,...

# Read_csv
## read_csv can read boath excel and csv file

In [ ]:
an = pd.read_csv('all_anime.csv')

In [ ]:
an.head()

,ID,S_ID,Title,Score,Rank,Popularity,Episodes,Start Date,End Date
0,1,52991,Sousou no Frieren,9.29,1.0,130,28,2023-09-29,2024-03-22
1,2,5114,Fullmetal Alchemist: Brotherhood,9.10,2.0,3,64,2009-04-05,2010-07-04
2,3,9253,Steins;Gate,9.07,3.0,14,24,2011-04-06,2011-09-14
3,4,38524,Shingeki no Kyojin Season 3 Part 2,9.05,4.0,21,10,2019-04-29,2019-07-01
4,5,39486,Gintama: The Final,9.05,5.0,1520,1,2021-01-08,2021-01-08

# read_excel can only read XMSX file

In [ ]:
ex = pd.read_excel("Courece_List.xlsx")

In [ ]:
ex

,Sr.No,Courece Name,Link,ETTC,Status
0,1,Deloitte Australia | Data Analytics | Forage,Link,1-1.5 Hours,Complete
1,2,Python for Beginners,Link,11 Hours,Inprocess
2,3,SQL for Data Analysis,Link,1 Hours,Pending
3,4,Python Libraries for Data Science,Link,7 Hours,Pending
4,5,Data Analytics with Excel,Link,3 to 8 Hours,Pending
5,6,Exploratory Data Analysis,Link,5 Hours,Pending
6,7,Data Processing and Visualisation,Link,15 Hours,Pending
7,8,Design effective reports in Power BI 2,Link,5.1 Hours,Pending
8,9,Cisco Introduction to Data Science,Link,6 Hours,Pending

In [ ]:
ex.head()

,Sr.No,Courece Name,Link,ETTC,Status
0,1,Deloitte Australia | Data Analytics | Forage,Link,1-1.5 Hours,Complete
1,2,Python for Beginners,Link,11 Hours,Inprocess
2,3,SQL for Data Analysis,Link,1 Hours,Pending
3,4,Python Libraries for Data Science,Link,7 Hours,Pending
4,5,Data Analytics with Excel,Link,3 to 8 Hours,Pending

In [ ]:
ex.tail()

,Sr.No,Courece Name,Link,ETTC,Status
4,5,Data Analytics with Excel,Link,3 to 8 Hours,Pending
5,6,Exploratory Data Analysis,Link,5 Hours,Pending
6,7,Data Processing and Visualisation,Link,15 Hours,Pending
7,8,Design effective reports in Power BI 2,Link,5.1 Hours,Pending
8,9,Cisco Introduction to Data Science,Link,6 Hours,Pending

# Read_json

In [74]:
jf = pd.read_json('anscombe.json')
jf.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [75]:
jf.tail()

   Series   X      Y
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89