In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 1. Adding Colum Name / Header

In [ ]:
col = ["sr","City","Institute","Subject","State","Time"]
a = pd.read_table("course.csv",sep=",",header=None,names=col)

In [ ]:
col = ["Sr","Age","Gender","Job","Num"]
a = pd.read_table("psd.user.txt",sep="|",header=None,names=col)

In [ ]:
a

      Sr  Age Gender            Job    Num
0      1   24      M     technician  85711
1      2   53      F          other  94043
2      3   23      M         writer  32067
3      4   24      M     technician  43537
4      5   33      F          other  15213
..   ...  ...    ...            ...    ...
938  939   26      F        student  33319
939  940   32      M  administrator  02215
940  941   20      M        student  97229
941  942   48      F      librarian  78209
942  943   22      M        student  77841

[943 rows x 5 columns]

# 2. Adding a New Colum

In [36]:
a.Job+"|"+a.Gender

0         technician|M
1              other|F
2             writer|M
3         technician|M
4              other|F
            ...
938          student|F
939    administrator|M
940          student|M
941        librarian|F
942          student|M
Length: 943, dtype: object

In [44]:
a["Age_Num"] = a["Age"].astype(str) + "|" + a.Num.astype(str)

In [47]:
a

      Sr  Age Gender            Job    Num   Age_Num
0      1   24      M     technician  85711  24|85711
1      2   53      F          other  94043  53|94043
2      3   23      M         writer  32067  23|32067
3      4   24      M     technician  43537  24|43537
4      5   33      F          other  15213  33|15213
..   ...  ...    ...            ...    ...       ...
938  939   26      F        student  33319  26|33319
939  940   32      M  administrator  02215  32|02215
940  941   20      M        student  97229  20|97229
941  942   48      F      librarian  78209  48|78209
942  943   22      M        student  77841  22|77841

[943 rows x 6 columns]

In [48]:
a.Age_Num

0      24|85711
1      53|94043
2      23|32067
3      24|43537
4      33|15213
         ...
938    26|33319
939    32|02215
940    20|97229
941    48|78209
942    22|77841
Name: Age_Num, Length: 943, dtype: object

In [49]:
m = pd.read_xml("animelist.xml")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

# 3. Deleteing colum

In [50]:
a

      Sr  Age Gender            Job    Num   Age_Num
0      1   24      M     technician  85711  24|85711
1      2   53      F          other  94043  53|94043
2      3   23      M         writer  32067  23|32067
3      4   24      M     technician  43537  24|43537
4      5   33      F          other  15213  33|15213
..   ...  ...    ...            ...    ...       ...
938  939   26      F        student  33319  26|33319
939  940   32      M  administrator  02215  32|02215
940  941   20      M        student  97229  20|97229
941  942   48      F      librarian  78209  48|78209
942  943   22      M        student  77841  22|77841

[943 rows x 6 columns]

In [57]:
# This will delete the Colom remprory
a.drop("Job",axis=1)

KeyError: "['Job'] not found in axis"

In [53]:
a

      Sr  Age Gender            Job    Num   Age_Num
0      1   24      M     technician  85711  24|85711
1      2   53      F          other  94043  53|94043
2      3   23      M         writer  32067  23|32067
3      4   24      M     technician  43537  24|43537
4      5   33      F          other  15213  33|15213
..   ...  ...    ...            ...    ...       ...
938  939   26      F        student  33319  26|33319
939  940   32      M  administrator  02215  32|02215
940  941   20      M        student  97229  20|97229
941  942   48      F      librarian  78209  48|78209
942  943   22      M        student  77841  22|77841

[943 rows x 6 columns]

In [55]:
# To permently delete
a.drop("Job",axis=1,inplace=True)

KeyError: "['Job'] not found in axis"

In [56]:
a

      Sr  Age Gender    Num   Age_Num
0      1   24      M  85711  24|85711
1      2   53      F  94043  53|94043
2      3   23      M  32067  23|32067
3      4   24      M  43537  24|43537
4      5   33      F  15213  33|15213
..   ...  ...    ...    ...       ...
938  939   26      F  33319  26|33319
939  940   32      M  02215  32|02215
940  941   20      M  97229  20|97229
941  942   48      F  78209  48|78209
942  943   22      M  77841  22|77841

[943 rows x 5 columns]

In [59]:
a.drop(["Sr","Gender"],axis=1,inplace=None)

     Age    Num   Age_Num
0     24  85711  24|85711
1     53  94043  53|94043
2     23  32067  23|32067
3     24  43537  24|43537
4     33  15213  33|15213
..   ...    ...       ...
938   26  33319  26|33319
939   32  02215  32|02215
940   20  97229  20|97229
941   48  78209  48|78209
942   22  77841  22|77841

[943 rows x 3 columns]

In [60]:
a

      Sr  Age Gender    Num   Age_Num
0      1   24      M  85711  24|85711
1      2   53      F  94043  53|94043
2      3   23      M  32067  23|32067
3      4   24      M  43537  24|43537
4      5   33      F  15213  33|15213
..   ...  ...    ...    ...       ...
938  939   26      F  33319  26|33319
939  940   32      M  02215  32|02215
940  941   20      M  97229  20|97229
941  942   48      F  78209  48|78209
942  943   22      M  77841  22|77841

[943 rows x 5 columns]

In [ ]:
a.drop(["Sr","Gender"],axis=1,inplace=True)

In [63]:
a

     Age    Num   Age_Num
0     24  85711  24|85711
1     53  94043  53|94043
2     23  32067  23|32067
3     24  43537  24|43537
4     33  15213  33|15213
..   ...    ...       ...
938   26  33319  26|33319
939   32  02215  32|02215
940   20  97229  20|97229
941   48  78209  48|78209
942   22  77841  22|77841

[943 rows x 3 columns]

In [71]:
a.drop(index=2,axis=1,inplace=True)

KeyError: '[2] not found in axis'

In [72]:
a

     Age    Num   Age_Num
0     24  85711  24|85711
1     53  94043  53|94043
3     24  43537  24|43537
4     33  15213  33|15213
5     42  98101  42|98101
..   ...    ...       ...
938   26  33319  26|33319
939   32  02215  32|02215
940   20  97229  20|97229
941   48  78209  48|78209
942   22  77841  22|77841

[942 rows x 3 columns]

In [73]:
a.drop([4,5,6,7],axis=0,inplace=True)

In [74]:
a

     Age    Num   Age_Num
0     24  85711  24|85711
1     53  94043  53|94043
3     24  43537  24|43537
8     29  01002  29|01002
9     53  90703  53|90703
..   ...    ...       ...
938   26  33319  26|33319
939   32  02215  32|02215
940   20  97229  20|97229
941   48  78209  48|78209
942   22  77841  22|77841

[938 rows x 3 columns]